# Generated by Django 4.2 on 2025-04-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=30)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='title_en',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
