# Generated by Django 4.2 on 2025-04-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_menuitem_shop_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/menu/items'),
        ),
    ]
