# Generated by Django 4.2 on 2025-08-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_menuitem_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='images/menu/categories')),
            ],
        ),
    ]
