# Generated by Django 4.2 on 2025-08-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
