# Generated by Django 4.2 on 2025-08-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_menuitem_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
