# Generated by Django 4.2 on 2025-08-22 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_shop_instagram_shop_location_shop_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.category'),
            preserve_default=False,
        ),
    ]
