# Generated by Django 4.2 on 2025-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
